name: bubblecam
description: BubbleCam - realtime photo sharing with likes & comments
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.2
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  timeago: ^3.6.1
  uuid: ^4.4.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
