// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJjAAt9NKLtJrTUu-ZCwDfMp8lu3IYF38',
    appId: '1:798686492351:web:2110179a0ce012cff5380a',
    messagingSenderId: '798686492351',
    projectId: 'bubblecam-9e138',
    authDomain: 'bubblecam-9e138.firebaseapp.com',
    databaseURL: 'https://bubblecam-9e138-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bubblecam-9e138.firebasestorage.app',
    measurementId: 'G-18FNNYPXC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlvi5g7p2YUiFlNzzOhegTE1P3eUH6Mww',
    appId: '1:798686492351:android:e2c4786f3ccacbd7f5380a',
    messagingSenderId: '798686492351',
    projectId: 'bubblecam-9e138',
    databaseURL: 'https://bubblecam-9e138-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bubblecam-9e138.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3ePPmP_PlYGnAWQ9oO5UI0J7PPT4s3Uw',
    appId: '1:798686492351:ios:9c67e6e5b15dba61f5380a',
    messagingSenderId: '798686492351',
    projectId: 'bubblecam-9e138',
    databaseURL: 'https://bubblecam-9e138-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bubblecam-9e138.firebasestorage.app',
    androidClientId: '798686492351-g4aeps8ef1ohamek2o3kb36dcjte81u7.apps.googleusercontent.com',
    iosClientId: '798686492351-0aotf7sjrces35b9cclod2vrejsfiupv.apps.googleusercontent.com',
    iosBundleId: 'com.example.bubblecam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3ePPmP_PlYGnAWQ9oO5UI0J7PPT4s3Uw',
    appId: '1:798686492351:ios:9c67e6e5b15dba61f5380a',
    messagingSenderId: '798686492351',
    projectId: 'bubblecam-9e138',
    databaseURL: 'https://bubblecam-9e138-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bubblecam-9e138.firebasestorage.app',
    androidClientId: '798686492351-g4aeps8ef1ohamek2o3kb36dcjte81u7.apps.googleusercontent.com',
    iosClientId: '798686492351-0aotf7sjrces35b9cclod2vrejsfiupv.apps.googleusercontent.com',
    iosBundleId: 'com.example.bubblecam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJjAAt9NKLtJrTUu-ZCwDfMp8lu3IYF38',
    appId: '1:798686492351:web:c308d710dbb38a16f5380a',
    messagingSenderId: '798686492351',
    projectId: 'bubblecam-9e138',
    authDomain: 'bubblecam-9e138.firebaseapp.com',
    databaseURL: 'https://bubblecam-9e138-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bubblecam-9e138.firebasestorage.app',
    measurementId: 'G-QJ068YY51D',
  );
}
